[package]
name = "spade"
version = "2.0.0"
authors = ["Stefan Altmayer <stoeoef@gmail.com>"]
description="Spatial datastructures like r-trees and delaunay triangulations for rust."
documentation = "https://docs.rs/spade/"
repository = "https://github.com/Stoeoef/spade"
readme = "README.md"
keywords = ["delaunay", "triangulation", "rtree", "geometry", "interpolation"]
license = "MIT/Apache-2.0"
edition = "2018"

[features]
serde_serialize = ["num/serde", "serde"]

[dependencies]
cgmath = "0.18"
nalgebra = "0.27"
num = "0.4"
clamp = "0.1"
smallvec = "1.2"
pdqselect = "0.1"
serde_derive = { version = "1.0", optional=true }
serde = { version = "1.0", optional=true, features=["rc", "serde_derive"] }

[dev-dependencies]
rand = "0.8"
rand_hc = "0.3"
serde_json = "1.0"
approx = "0.5"
criterion = "0.3"

[profile.bench]
opt-level = 3
debug-assertions = false

[badges]
maintenance = { status = "passively-maintained" }

[[bench]]
name = "delaunay"
harness = false
